from app.schemas.farmers import FarmerResponse,FarmerCreate,FarmerUpdate
from app.schemas.farms import FarmCreate, FarmResponse, FarmUpdate
from app.schemas.fields import FieldCreate,FieldResponse,FieldUpdate
from app.schemas.crop_cycles import CCCreate, CCResponse, CCUpdate
from app.schemas.irrigation_records import IrrigationLogCreate,IrrigationLogResponse,IrrigationLogUpdate
from app.schemas.recommendation import RecommendationCreate,RecommendationResponse,RecommendationUpdate
from app.schemas.soil_moisture import SoilMoistureCreate,SoilMoistureResponse,SoilMoistureUpdate
from app.schemas.weather_data import WeatherDataCreate,WeatherDataResponse,WeatherDataUpdate